name: Run unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build and Start Services
        run: |
          docker-compose -f docker-compose-depl.yml up -d --build mantap

      - name: Download wait-for-it script
        run: |
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Wait for PostgreSQL to be ready
        run: |
          sleep 10
          ./wait-for-it.sh localhost:5432 --timeout=120 --strict -- echo "PostgreSQL is up"

      - name: Run migrations
        run: |
          docker-compose -f docker-compose-depl.yml exec -T mantap sh -c 'migrate -path db/migration -database "$(DATABASE_URL)" -verbose up'

      - name: Run Tests
        run: |
          docker-compose -f docker-compose-depl.yml exec -T mantap sh -c 'go test -v -cover ./...'

      - name: Stop Services
        if: always()
        run: |
          docker-compose -f docker-compose-depl.yml down --rmi all